genesis-file="/opt/besu/genesis.json"
data-path="/opt/besu/data"
node-private-key-file="/opt/besu/key"
network-id=20260720
p2p-enabled=true
p2p-host="0.0.0.0"
p2p-port=30303
discovery-enabled=false
sync-min-peers=1
static-nodes-file="/opt/besu/static-nodes.json"
rpc-http-enabled=false
rpc-ws-enabled=false
graphql-http-enabled=false
metrics-enabled=true
metrics-host="0.0.0.0"
metrics-port=9545
host-allowlist=["validator-3","localhost","127.0.0.1"]
min-gas-price=0
tx-pool-no-local-priority=true
logging="INFO"
